services:
  #  web:
  #    build: .
  #    image: chat_web
  #    container_name: chat_web
  #    ports:
  #      - "8000:82"          # хост:контейнер
  #    depends_on:
  #      db:
  #        condition: service_healthy
  #    env_file:
  #        - .env
  #    entrypoint: ["/app/entrypoint.sh"]
  #    command: python /app/web/manage.py runserver 0.0.0.0:82

  db:
    image: postgres:15
    container_name: chat_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10          # больше попыток — надёжнее при первом запуске
      start_period: 10s    # даёт postgres 10 секунд "на разогрев" до начала проверок
    ports:
      - "5433:5432"   # хост 5433 → контейнер 5432


  adminer:
    image: adminer:latest
    container_name: chat_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"                       #8080 внутри контейнера
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha        # опционально — красивая тема
    depends_on:
      - db


  redis:
    image: redis:7-alpine
    container_name: chat_redis
    ports:
      - "6379:6379"        # хост:контейнер
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5


  worker:
    build: .
    container_name: chat_worker
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/web
    command: celery -A web.config worker -l info




volumes:
  pgdata:
  redisdata: