[project]
name = "candidateschat"
version = "0.1.0"
description = ""
authors = [
    {name = "ilyab",email = "i-baykov@internet.ru"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django (>=5.0,<6.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "celery (>=5.6.0,<6.0.0)",
    "django-cors-headers (>=4.9.0,<5.0.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "django-debug-toolbar (>=6.1.0,<7.0.0)",
    "psycopg2 (>=2.9.11,<3.0.0)",
    "django-filter (>=25.2,<26.0)",
    "django-redis (>=6.0.0,<7.0.0)",
    "django-celery-results (>=2.6.0,<3.0.0)",
    "gunicorn (>=23.0.0,<24.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-django (>=4.11.1,<5.0.0)",
    "django-admin-extra-buttons (>=2.1.2,<3.0.0)",
    "pdfplumber (>=0.11.9,<0.12.0)",
    "drf-spectacular (>=0.29.0,<0.30.0)",
    "pytest-mock (>=3.15.1,<4.0.0)",
    "pytz (>=2026.1.post1,<2027.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.base"
pythonpath = ["web"]
markers = ["slow: помечает тесты, которые выполняются долго"]