# Generated by Django 5.2.10 on 2026-01-27 14:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0004_alter_messagerole_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField(db_index=True)),
                ('vacancy_id', models.IntegerField(db_index=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Уникальная ссылка для доступа кандидата', unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('status', models.ForeignKey(help_text='Статус интервью', on_delete=django.db.models.deletion.CASCADE, to='reference.interviewstatus')),
            ],
            options={
                'verbose_name': 'Интервью',
                'verbose_name_plural': 'Интервью',
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Текст вопроса')),
                ('order', models.PositiveIntegerField(help_text='Порядок вопроса в интервью')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interview')),
                ('status', models.ForeignKey(help_text='Статус ответа на вопрос', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='reference.answerstatus')),
            ],
            options={
                'verbose_name': 'Вопрос интервью',
                'verbose_name_plural': 'Вопросы интервью',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InterviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Текст сообщения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interviews.interview')),
                ('role', models.ForeignKey(help_text='Роль отправителя сообщения', on_delete=django.db.models.deletion.PROTECT, to='reference.messagerole')),
                ('question', models.ForeignKey(blank=True, help_text='Вопрос, к которому относится сообщение (если применимо)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='interviews.interviewquestion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text='Текст ответа кандидата')),
                ('score', models.FloatField(blank=True, help_text='Оценка ответа (будет от ИИ или админа)', null=True)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Время ответа')),
                ('interview_question', models.OneToOneField(help_text='Вопрос, на который дан ответ', on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interviews.interviewquestion')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['token'], name='interviews__token_837f20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together={('candidate_id', 'vacancy_id')},
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['interview', 'status'], name='interviews__intervi_86a483_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewquestion',
            unique_together={('interview', 'order')},
        ),
        migrations.AddIndex(
            model_name='interviewmessage',
            index=models.Index(fields=['interview', 'created_at'], name='interviews__intervi_d2aacc_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewmessage',
            index=models.Index(fields=['question', 'created_at'], name='interviews__questio_261da7_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewmessage',
            index=models.Index(fields=['role'], name='interviews__role_id_fc8cdf_idx'),
        ),
    ]
