# Generated by Django 5.2.9 on 2025-12-22 22:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='ID кандидата во внешней системе', max_length=64, unique=True)),
                ('full_name', models.CharField(help_text='ФИО кандидата', max_length=255)),
                ('contacts', models.CharField(blank=True, help_text='Контакты кандидата', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='Внешний ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_link', models.URLField(help_text='Уникальная ссылка для доступа кандидата')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='interviews.candidate')),
                ('status', models.ForeignKey(help_text='Статус интервью', on_delete=django.db.models.deletion.CASCADE, to='reference.interviewstatus')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='interviews.vacancy')),
            ],
            options={
                'verbose_name': 'Интервью',
                'verbose_name_plural': 'Интервью',
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Текст вопроса')),
                ('order', models.PositiveIntegerField(help_text='Порядок вопроса в интервью')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interview')),
                ('status', models.ForeignKey(help_text='Статус ответа на вопрос', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='reference.answerstatus')),
            ],
            options={
                'verbose_name': 'Вопрос интервью',
                'verbose_name_plural': 'Вопросы интервью',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text='Текст ответа кандидата')),
                ('score', models.FloatField(blank=True, help_text='Оценка ответа (будет от ИИ или админа)', null=True)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Время ответа')),
                ('interview_question', models.OneToOneField(help_text='Вопрос, на который дан ответ', on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interviews.interviewquestion')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
        migrations.CreateModel(
            name='InterviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Текст сообщения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Время создания сообщения')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interviews.interview')),
                ('role', models.ForeignKey(help_text='Роль отправителя сообщения (кандидат, ИИ-агент, система)', on_delete=django.db.models.deletion.PROTECT, to='reference.messagerole')),
            ],
            options={
                'verbose_name': 'Сообщение интервью',
                'verbose_name_plural': 'Сообщения интервью',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['interview', 'created_at'], name='interviews__intervi_d2aacc_idx'), models.Index(fields=['role'], name='interviews__role_id_fc8cdf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['interview', 'status'], name='interviews__intervi_86a483_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewquestion',
            unique_together={('interview', 'order')},
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['token_link'], name='interviews__token_l_3659c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together={('candidate', 'vacancy')},
        ),
    ]
