# Generated by Django 5.2.9 on 2025-12-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_description',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о вакансии'),
        ),
    ]
