# Generated by Django 5.2.10 on 2026-03-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='order',
            field=models.IntegerField(help_text='Порядок вопроса в интервью'),
        ),
    ]
