# Generated by Django 5.2.9 on 2025-12-24 16:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_vacancy_vacancy_description'),
        ('reference', '0003_alter_interviewstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='interviewmessage',
            name='question',
            field=models.ForeignKey(blank=True, help_text='Вопрос, к которому относится сообщение (если применимо)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='interviews.interviewquestion'),
        ),
        migrations.AlterField(
            model_name='interviewmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='interviewmessage',
            name='role',
            field=models.ForeignKey(help_text='Роль отправителя сообщения', on_delete=django.db.models.deletion.PROTECT, to='reference.messagerole'),
        ),
        migrations.AddIndex(
            model_name='interviewmessage',
            index=models.Index(fields=['question', 'created_at'], name='interviews__questio_261da7_idx'),
        ),
    ]
