# Generated by Django 5.2.10 on 2026-01-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_interviewmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_text',
            field=models.TextField(blank=True, help_text='Текст резюме кандидата', null=True),
        ),
    ]
