# Generated by Django 5.2.9 on 2025-12-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Машинный код статуса ответа (например: pending, answered, scored).', max_length=32, unique=True)),
                ('title', models.CharField(help_text='Человекочитаемое название статуса ответа.', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Флаг активности статуса. Неактивные статусы не должны назначаться новым ответам.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения в админке.')),
            ],
            options={
                'verbose_name': 'Answer status',
                'verbose_name_plural': 'Answer statuses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InterviewStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Машинный код статуса. Используется в логике приложения (например: draft, in_progress, completed).', max_length=32, unique=True)),
                ('title', models.CharField(help_text='Человекочитаемое название статуса для админки и UI.', max_length=64)),
                ('is_terminal', models.BooleanField(default=False, help_text='Признак терминального статуса. Если True — интервью считается завершённым, переходы запрещены.')),
                ('is_active', models.BooleanField(default=True, help_text='Флаг активности статуса. Неактивные статусы не должны использоваться в новых интервью.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения в админке и интерфейсах. Не используется для бизнес-логики переходов.')),
            ],
            options={
                'verbose_name': 'Interview status',
                'verbose_name_plural': 'Interview statuses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MessageRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Машинный код роли. Используется в коде приложения (например: candidate, agent, system).', max_length=32, unique=True)),
                ('title', models.CharField(help_text='Человекочитаемое название роли для админки и UI.', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Флаг активности. Неактивные роли не должны использоваться в новых сообщениях.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения в админке, фильтрах и интерфейсах.')),
            ],
            options={
                'verbose_name': 'Message role',
                'verbose_name_plural': 'Message roles',
                'ordering': ['order'],
            },
        ),
    ]
