# Generated by Django 5.2.9 on 2025-12-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerstatus',
            options={'ordering': ['order'], 'verbose_name': 'Статус ответа', 'verbose_name_plural': 'Статусы ответов'},
        ),
        migrations.AlterModelOptions(
            name='messagerole',
            options={'ordering': ['order'], 'verbose_name': 'Роль сообщения', 'verbose_name_plural': 'Роль сообщений'},
        ),
    ]
