# Generated by Django 5.2.9 on 2025-12-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_alter_answerstatus_options_alter_messagerole_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewstatus',
            options={'ordering': ['order'], 'verbose_name': 'Статус интервью', 'verbose_name_plural': 'Статусы интервью'},
        ),
    ]
