# Generated by Django 5.2.10 on 2026-01-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_alter_interviewstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagerole',
            options={'ordering': ['order'], 'verbose_name': 'Роль отправителя сообщения', 'verbose_name_plural': 'Роли отправителей сообщений'},
        ),
    ]
