# Generated by Django 5.2.10 on 2026-03-03 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_email', models.EmailField(max_length=254, verbose_name='Email кандидата')),
                ('candidate_name', models.CharField(max_length=255, verbose_name='Имя кандидата')),
                ('recruiter_email', models.EmailField(max_length=254, verbose_name='Email рекрутера')),
                ('start_datetime', models.DateTimeField(verbose_name='Начало интервью')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)')),
                ('location', models.CharField(default='Google Meet', max_length=500, verbose_name='Место/ссылка')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('gmail_message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gmail Message ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Слот интервью',
                'verbose_name_plural': 'Слоты интервью',
                'ordering': ['start_datetime'],
            },
        ),
    ]
